server:
  port: 8083

spring:
  application:
    name: inventory-service

security:
  service-api-key: ${SERVICE_API_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
