server:
  port: 8082

spring:
  application:
    name: payment-service

services:
  notification:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
